version: '3.7'

services:
  django_gunicorn:
    volumes:
      - static:/static
      - db_volume:/app/db_data
    env_file:
      - .env
    build:
      context: Boulderjager
    ports:
      - "8000:8000"
  nginx:
    build: ./nginx
    volumes:
      - static:/static
    ports:
        - "80:80"
    depends_on:
        - django_gunicorn

volumes:
    static:
    db_volume: