version: '3.7'

services:
  django_gunicorn:
    volumes:
      - static:/static
      - db_volume:/app/db_data
    env_file:
      - .env
    build:
      context: Boulderjager
    ports:
      - "8000:8000"
  nginx:
    build: ./nginx
    volumes:
      - static:/static
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf:ro
      - ./certbot/www/:/var/www/certbot/:ro
    ports:
        - "80:80"
        - "443:443"
    restart: always
    depends_on:
        - django_gunicorn
  certbot:
    image: certbot/certbot:latest
    volumes:
      - ./certbot/www/:/var/www/certbot/:rw

volumes:
    static:
    db_volume:
